### ISSUE TITLE
error emssages on active servers after long uptime

### ISSUE THREAD

**Issue by egzen** [DarkstarProject/xiNavmeshes#9]
By long uptime I don't just mean a servers uptime I mean if a zone stays empty this issue basically won't happen. Its like zones don't exist when people aren't in them. Anyway, in a zone seeing a lot of player traffic for many hours, the console log will begin to fill with navmesh related error messages where previously we were not having issues. 

`CNavMesh::findRandomPath startRef is invalid (-574.346985, -0.593000, -473.778015) (132)`

`CNavMesh::findPath Couldn't find path (-254.328995, 32.438999, -433.661011)->(-250.373337, 2.877833, -414.505402) (254)`

**Comment by teschnei** [comment]
reopen the issue in darkstar (even though its kind of more relevant here, I prefer to keep them all in one place)

and yeah, empty zones don't tick so nothing happens in them
